version: "3.9"

services:
  web:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../:/opt/TreeMenu/
    entrypoint: docker/local/entrypoint.sh
    ports:
      - "8000:8000"